import type { Property } from '@/types'

export const DEMO_PROPERTIES: Property[] = [
  {
    id: 'demo-1',
    agent_id: 'agent-1',
    title: 'Beachfront Villa — Koh Tao',
    description: 'Stunning 4-bedroom villa with panoramic Gulf of Thailand views. Private infinity pool, direct beach access, and fully furnished with designer interiors. Ideal for luxury living or high-yield short-term rental.',
    type: 'villa',
    status: 'for_sale',
    price: 12500000,
    bedrooms: 4,
    bathrooms: 3,
    area_sqm: 320,
    address: '88 Moo 1, Sairee Beach',
    city: 'Koh Tao',
    province: 'Surat Thani',
    country: 'Thailand',
    lat: 10.0956,
    lng: 99.8403,
    featured: true,
    images: [
      'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=900&q=80',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=900&q=80',
    ],
    amenities: ['Pool', 'Sea View', 'Beach Access', 'Parking', 'Air Conditioning', 'WiFi'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'demo-2',
    agent_id: 'agent-1',
    title: 'Modern Condo — Chaweng, Koh Samui',
    description: 'Sleek 2-bedroom high-floor condo in the heart of Chaweng. Floor-to-ceiling windows, resort facilities, and walking distance to the beach. Perfect for digital nomads or investment.',
    type: 'condo',
    status: 'for_sale',
    price: 3850000,
    bedrooms: 2,
    bathrooms: 2,
    area_sqm: 85,
    address: '12/4 Chaweng Beach Road',
    city: 'Koh Samui',
    province: 'Surat Thani',
    country: 'Thailand',
    lat: 9.5300,
    lng: 100.0586,
    featured: true,
    images: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=900&q=80',
      'https://images.unsplash.com/photo-1560448075-bb485b067938?w=900&q=80',
    ],
    amenities: ['Pool', 'Gym', 'Security', 'Parking', 'Sea View'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'demo-3',
    agent_id: 'agent-1',
    title: 'Tropical House — Lamai',
    description: 'Charming 3-bed Thai-style house nestled in tropical gardens. Quiet soi, 5 min drive to Lamai Beach. Ideal family home or long-term rental investment.',
    type: 'house',
    status: 'for_rent',
    price: 35000,
    bedrooms: 3,
    bathrooms: 2,
    area_sqm: 180,
    address: '22 Soi Lamai Garden',
    city: 'Koh Samui',
    province: 'Surat Thani',
    country: 'Thailand',
    lat: 9.4740,
    lng: 100.0528,
    featured: false,
    images: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=900&q=80',
    ],
    amenities: ['Garden', 'Parking', 'Air Conditioning', 'WiFi', 'Pet Friendly'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'demo-4',
    agent_id: 'agent-1',
    title: 'Sea View Land — Nathon Hill',
    description: '800 sqm titled land (Chanote) on elevated hillside with spectacular sunset views over Nathon Bay. Buildable with ready utilities. Rare ownership opportunity.',
    type: 'land',
    status: 'for_sale',
    price: 4200000,
    bedrooms: null,
    bathrooms: null,
    area_sqm: 800,
    address: 'Nathon Hill Road',
    city: 'Koh Samui',
    province: 'Surat Thani',
    country: 'Thailand',
    lat: 9.5340,
    lng: 99.9770,
    featured: false,
    images: [
      'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=900&q=80',
    ],
    amenities: ['Sea View', 'Chanote Title', 'Road Access', 'Utilities'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'demo-5',
    agent_id: 'agent-1',
    title: 'Luxury Pool Villa — Bophut',
    description: 'Award-winning 5-bed villa in prestigious Bophut Hills. Architect-designed with infinity pool, home cinema, and 270° sea views. Gated community with 24hr security.',
    type: 'villa',
    status: 'for_sale',
    price: 28000000,
    bedrooms: 5,
    bathrooms: 5,
    area_sqm: 650,
    address: 'Bophut Hills Estate',
    city: 'Koh Samui',
    province: 'Surat Thani',
    country: 'Thailand',
    lat: 9.5460,
    lng: 100.0210,
    featured: true,
    images: [
      'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=900&q=80',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=900&q=80',
    ],
    amenities: ['Pool', 'Sea View', 'Home Cinema', 'Gym', 'Gated', '24hr Security', 'Smart Home'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'demo-6',
    agent_id: 'agent-1',
    title: 'Studio Condo — Bang Rak',
    description: 'Smart studio in a popular tourist area near the famous Samui ferry pier. High rental occupancy, fully furnished, strong ROI track record.',
    type: 'condo',
    status: 'for_sale',
    price: 1650000,
    bedrooms: 1,
    bathrooms: 1,
    area_sqm: 38,
    address: 'Bang Rak Beach Complex',
    city: 'Koh Samui',
    province: 'Surat Thani',
    country: 'Thailand',
    lat: 9.5460,
    lng: 100.0480,
    featured: false,
    images: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=900&q=80',
    ],
    amenities: ['Pool', 'Security', 'Furnished', 'WiFi'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]
